name: Aikido Security Scan

on:
  pull_request:
    

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Aikido scan
        run: aikido scan
        env:
          AIKIDO_API_KEY: ${{ secrets.AIKIDO_API_KEY }}
